version: "3.8"
services:
  radar:
    build: radar-totk
    ports:
     - "3008:3008"
    volumes:
     - ./totk-romfs:/romfs:ro
  objmap:
    build: objmap-totk
    ports:
     - "8080:8080"
    environment:
      - VUE_APP_RADAR_URL=http://localhost:3008
      - VUE_APP_GAME_FILES=http://localhost:8080/game_files
